// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SQLAid
{
    internal sealed partial class Vsix
    {
        public const string Id = "55ee9134-b925-4767-aab2-ed675fdfd978";
        public const string Name = "SQL Aid";
        public const string Description = @"SQL Aid is a SQL Server Management Studio Add-in.";
        public const string Language = "en-US";
        public const string Version = "2.0.1";
        public const string Author = "duong.nguyen";
        public const string Tags = "ssms";
    }
}
