name: build

on:
  release:
    types: [created]
    branches:
      - "main"

jobs:
  build:
    name: Build
    runs-on: windows-2019
    env:
      Configuration: SSMS19
      Project: src/SQLAid.sln
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install Visual Studio Build Tools
      uses: microsoft/setup-msbuild@v1
      
    - name: Setup .NET build dependencies
      uses: timheuer/bootstrap-dotnet@v1
      with:
        nuget: 'false'
        sdk: 'false'
        msbuild: 'true'
    
    - name: Restore NuGet packages
      run: nuget restore src/SQLAid.sln
   
    - name: Build
      run: msbuild src/SQLAid.sln /p:Configuration=$env:Configuration

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ github.event.repository.name }}.vsix
        path: src/SQLAid/bin/**/*.vsix

    - name: Upload to GitHub Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        files: src/SQLAid/bin/**/*.vsix
        tag_name: ${{ github.ref_name }}

